### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by mujingfatasy** [frankih9/Planar_Baluns#1]
I'm now running your example script but it thow an error：'NoneType' object is not subscriptable  at line 30 of Valid_Check.py, what's wrong with this? could you give me a help

**Comment by mujingfatasy** [comment]
length = 2*CO.get_bounding_box()[1][0]

**Comment by frankih9** [comment]
The gdspy I used was circa 200 BC.  Will update codes to the latest gdspy soon.  The issues are mainly with gds library, cell creation, and cell referencing.

**Comment by frankih9** [comment]
Updated scripts for gdspy 1.6.12
